// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsBrushesColorPicker
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsBrushesColorPickerPackageCmdSetString = "5e9b6f9d-5d5c-4b0b-9e5c-1e2f8d5a9b11";
        public static Guid guidVsBrushesColorPickerPackageCmdSet = new Guid(guidVsBrushesColorPickerPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OtherWindowsGroup = 0x1020;
        public const int cmdidShowVsBrushesColorDialog = 0x0100;
    }
}
